In [ ]:
import numpy as np
a = np.array([20,30,40,100,21])
b = np.array([60,70,80,90,110])
print(a)
print(b)
print(a+b)
# slicing
print(a[0:3])   # covers 0, 1, 2nd index only
print(a[3:]) # till end from 3rd index; similary [:3] for 0 to 3


[ 20  30  40 100  21]
[ 60  70  80  90 110]
[ 80 100 120 190 131]
[20 30 40]
[100  21]


In [4]:
import numpy as np
c = np.array([[40,30,20,30],[30,60,70,100],[110,210,310,410]])
print(c[1,2:]) # 1st index wala array ke 2nd index tk ke baad
print(c[0:2,0:2]) # first 2 in 0th and 1st index elements
print(c[2,2]) # 310
print(type(c)) # <class 'numpy.ndarray'> ; where nd means n-dimensional

[ 70 100]
[[40 30]
 [30 60]]
310
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[40,30,20,30],[30,60,70,100]])
# Attributes of numpy
print(np.shape(arr)) # (2,4)
print(np.size(arr)) # 8 (total elements)
print(np.ndim(arr)) # 2 (2-d array)
print(arr.dtype) # int64

(2, 4)
8
2
int64


In [ ]:
# Inspecting an Array

a = [30,40,50,60,20]
arr1 = np.array(a)
print(arr)
print(arr.shape) # (5,) dont show 1 
print(len(arr1)) # 5
b = [[30,40],[50,60]]
arr2 = np.array(b)
print(arr2)
print(len(arr2)) # 2 
print(np.size(arr2)) # 4
print(arr2.astype(str)) # conversion to string


[30 40 50 60 20]
(5,)
5
[[30 40]
 [50 60]]
2
4
[['30' '40']
 ['50' '60']]


In [25]:
# Mathematical Operations and Functions on Arrays
a = [[30,40],[60,20]]
arr1 = np.array(a)
b = [[10,20],[30,20]]
arr2 = np.array(b)

# mathematical operations
print(arr1+arr2)
print(np.add(arr1,arr2))
# print(arr1-arr2)
# print(np.subtract(arr1,arr2))
# print(arr1*arr2)
# print(np.multiply(arr1,arr2))
# print(arr1/arr2)
# print(np.divide(arr1,arr2))
arr3 = np.array([3])
print(np.power(arr1,arr3))
arr4 = np.array([1,4,9,16])
print(np.sqrt(arr4)) # notice: you got result in float; you can convert into int using astype

[[40 60]
 [90 40]]
[[40 60]
 [90 40]]
[[ 27000  64000]
 [216000   8000]]
[1. 2. 3. 4.]


In [ ]:
# Combining and Splitting Arrays
# concatenate
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5,5],[3,4]])
print(np.concatenate([arr1,arr2]))  # same when axis = 0 ; same as vertically stack
print(np.concatenate([arr1,arr2], axis=1)) # same as horizontally stack

print(np.vstack([arr1,arr2]))
print(np.hstack([arr1,arr2]))

# Splitting
a = np.array([20,30,50,30,12,21])
# print(np.array_split(a,3)) # jab tk equally ho skta hai tb tk hoga fir single single split hone lagega
b = np.array_split(a,3)
print(b[1]) 

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  4]]
[[30 40  5  5]
 [50 60  3  4]]
[[30 40]
 [50 60]
 [ 5  5]
 [ 3  4]]
[[30 40  5  5]
 [50 60  3  4]]
[50 30]


In [43]:
# Adding and Removing
# Append
a = np.array([[20,40],[60,80]])
print(np.append(a,90)) # [20 40 60 80 90]
print(np.append(a,[90,100])) # [ 20  40  60  80  90 100]
# therefore first converts to 1-D then append

# Insert
print(np.insert(a,1,99)) # [20 99 40 60 80] i.e array,index,value

print(np.insert(a,1,[50,60],axis=1)) # column wise added elements
print(np.insert(a,1,[50,60],axis=0)) # row wise added elements ; if we'd wrote only [50] then dono place me 50 50 aa jata not single value

# Delete
print(np.delete(a,1)) # [20 60 80] 
print(np.delete(a,1,axis=1)) # [[20]
                             #  [60]]

[20 40 60 80 90]
[ 20  40  60  80  90 100]
[20 99 40 60 80]
[[20 50 40]
 [60 60 80]]
[[20 40]
 [50 60]
 [60 80]]
[20 60 80]
[[20]
 [60]]
